### PR TITLE
fixed lanbot erasing atow

### PR DESCRIPTION
**Pull request by benrandall**

### CODE REVIEW

**Comment by ThomasGaubert** [comment]
I'll actually look at this later, but make sure your PR passes the tests.

**Comment by benrandall** [comment]
I've never used git before

**Comment by ThomasGaubert** [comment]
Check out: https://travis-ci.org/ThomasGaubert/hubot-aotw/builds/139575851

You can see which tests are failing and the expected output.

**Comment by ThomasGaubert** [comment]
Closing since this addresses a problem which doesn't exist (at least in the form described).

Thanks for the PR, though!

**Pull request closed without merging**
